//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05._04.Exam.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoverSheet
    {
        public int TurnoverID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CassetteID { get; set; }
        public Nullable<System.DateTime> GiveOutDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Videoteka Videoteka { get; set; }
    }
}
