//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05._04.Exam.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videoteka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videoteka()
        {
            this.TurnoverSheet = new HashSet<TurnoverSheet>();
        }
    
        public int CassetteID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public string Availability { get; set; }
    
        public virtual ClassificationCode ClassificationCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnoverSheet> TurnoverSheet { get; set; }
    }
}
